import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="style.css" />
      </Head>
      <div className="p-12">
        <p className="text-red-500">test tailwindd</p>
    </div>
    </div>
  );
};

export default Home;